version: "3"

services:
  app:
    container_name: appBackend
    build:
      context: ../
    ports:
      - "8080:3000"
    links:
      - mysql-dev
    depends_on:
      - mysql-dev
    restart: always
    command: npm start

  mysql-dev:
    container_name: mysqlBackend
    build: ./sql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paises
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8060:80
    environment:
      - PMA_HOST=mysql-dev
      - MYSQL_ROOT_PASSWORD= root
    depends_on:
      - mysql-dev
